name: coverage

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true

    name: PHP Code Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Execute coverage
        run:
          php artisan key:generate
          php artisan test --compact --coverage --min=100
