name: style

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true

    name: Style Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run PHPCS
        run: vendor/bin/pint
